version: '3'

services:
    redis:
        container_name: algo_redis
        image: redis
        restart: always
    mysql:
        container_name: algo_mysql
        # mysql:8 sucks
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
          # data/mysql is put in the host to store the db data
          # - data/mysql:/var/lib/mysql
          
          # anonymous volume
          - /var/lib/mysql
    algo_server:
        build: .
        container_name: algo_server
        image: algo_server
        restart: always
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        links: 
          - mysql
          - redis
        depends_on:
          - mysql
          - redis
        ports:
          - '3000:3000'
          - '3001:3001'
        command: bash -c "./server/start_server.sh"

# volumes:
#   dbdata:
#     # non-persistent db data
#     driver: local
