  # Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - server-{{ checksum "server/package.json" }}
          - server-
      - run:
          name: Install server packages
          command: cd server && yarn install
      - save_cache:
          paths:
            - server/node_modules
          key: server-{{ checksum "server/package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - server
  test_server:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running server eslint checks
          command: cd server && yarn lint
      - run:
          name: Running server tests
          command: cd server && yarn test
workflows:
  version: 2
  build:
    jobs:
      - prepare
      - test_server:
          requires:
          - prepare