  # Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: verify docker compose build
          command: |
            docker-compose up
  test_client:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running client eslint checks
          command: cd client && yarn lint
  test_server:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running server eslint checks
          command: cd server && yarn lint
      - run:
          name: Running server tests
          command: cd server && yarn test
workflows:
  version: 2
  build:
    jobs:
      - prepare
      - test_client:
          requires:
          - prepare
